# -*- coding: utf-8 -*-
"""2022_09_15_image_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16pLt6Pq9IzE3r_OfXyX3TxBHeL08v5sf
"""

import numpy
import cv2
import math

img = cv2.imread('assets\car1.jpg', cv2.IMREAD_GRAYSCALE)

cv2.imshow(img)

print(img.max())
print(img.min())
print(img.shape)

for row in range(img.shape[0]):
  for column in range(img.shape[1]):
    eachPixel = img.item(row,column)

    if eachPixel > 155:
      img.itemset((row,column), img.max())
    else:
      img.itemset((row,column), img.min())

cv2.imshow(img)